### ISSUE TITLE
how do i compile it into a program 

### ISSUE THREAD

**Issue by elazzzzyy** [iklevente/WebhookDiscordTokenGrabber#1]
title

**Comment by iklevente** [comment]
In Grabbing.cs at line 140 paste your own discord webhook url and compile the program in Visual Studio by pressing Ctrl + Shift + B.

The executable should be in the project's bin/release folder.

**Comment by elazzzzyy** [comment]
it doesn't build. WebhookDiscordTokenGrabber-master\Grabbing.cs(28,30,28,30): error CS1002: ; expected

**Comment by elazzzzyy** [comment]
new issue [https://gyazo.com/fef7d4f3e9c12d5a040a28709e3d346b](url)

**Comment by iklevente** [comment]
It compiles successfully for me. Error CS1002 means that it expects a semicolon. But I don't get that error on my side.

I downloaded the GitHub version and I literally only changed line 140, compiled it and it works.
[Here](https://imgur.com/a/L6WAf7n) is a picture how it looks like for me.

Could you please provide me a picture or your entire project to see if I can help?
I can also compile it for you with you webhook, if nothing works.

**Comment by iklevente** [comment]
It compiles successfully for me. Error CS1002 means that it expects a semicolon. But I don't get that error on my side.

I downloaded the GitHub version and I literally only changed line 140, compiled it and it works.
[Here](https://imgur.com/a/oR3Sn7C) is a picture how it looks like for me.

Could you please provide me a picture or your entire project to see if I can help?
I can also compile it for you with you webhook, if nothing works.

**Comment by elazzzzyy** [comment]
![image](https://user-images.githubusercontent.com/57583188/91906337-ed18c480-ec9f-11ea-8eb7-474b286eb300.png)
this

**Comment by iklevente** [comment]
You don't need ""CK DI;" at line 28. (Only: return;)
You also don't need the entire line 32. (DropboxToken) I accidentally leaved that from one of my other projects, but that should not interfere.

**Comment by elazzzzyy** [comment]
removed CK DI, kept return; deleted line 32 entirely and my discord webhook is in 138 where it should be, now as previous whenever I try to build I get cs2012 access denied error, AV exclusions, running as admin, folder is set so everyone has full permissions.

**Comment by iklevente** [comment]
Antivirus will detect it, since it's a password stealer, unless you can encrypt/obfuscate the binary somehow.
Disable the antivirus and try it again, because sometimes AV's can block and deny access from malwares.

[This](https://stackoverflow.com/questions/37552769/error-cs2012-cannot-open-executable-path-access-to-executable-path-denied) might could also help you.

**Comment by elazzzzyy** [comment]
I got it to work by excluding the folder i was going to move it to, moved it there, deleted bin/obj, opened vsc as admin, build, it generated the exe and successfully pasted my token into the discord however some characters are unrecognized & appear as boxes.

**Comment by iklevente** [comment]
Do you mean that the gathered token which is now visible on your webhooked discord server text channel is not showing correctly?

**Comment by elazzzzyy** [comment]
For reference; I do have 2FA and SMS auth on, on my stable discord account which is the token it grabbed despite not being open or idle (which is fine) however the token just said "invalid" when i entered it into a chat exporter which it never has done before, i have had issues using tokens with the chat exporter if 2FA is on likely same goes for SMS auth. Unless i can get a tool that logs me in instead of being a chat exporter that could also possibly work.

**Comment by iklevente** [comment]
I should be able to get tokens no matter that 2FA or SMS auth is enabled. But after you got the token and you want to login with it, you will not be able to, because discord thinks that you provided the password (which was actually the token) and now it wants your 2FA..

**Comment by iklevente** [comment]
Also I have no idea what chat exporter are you talking about. And I have never coded any exception that would throw "invalid".

I will make you a tutorial video about how I do it tomorrow or a day later, if you want that.

**Comment by elazzzzyy** [comment]
Alright, I'm using raid-toolbox, and using the token selector I pasted my token and pressed log-in it took me to discord's canary login page online and refreshed a bunch and changed from /login to /app and back to login. If you know how to log-in to a token please let me know.

**Comment by iklevente** [comment]
The use of this program is to export and send a discord stored login token on the computer to a given webhook connected discord server's text channel.

After you got that long string of letters (--> token) [here](https://youtu.be/FmXMGCRpw50) is a video how to login with it, instead of using normal email & password login.
